-- Database: 'cse 340 project', public schema

-- Rebuild Script

-- 0. Drop ENUM type if it exists, and recreate it
DROP TYPE IF EXISTS public.account_type;
CREATE TYPE public.account_type AS ENUM (
    'Client',
    'Employee',
    'Admin'
);

-- 1. Drop and Create 'classification' Table
DROP TABLE IF EXISTS public.classification CASCADE;
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 2. Drop and Create 'inventory' Table
DROP TABLE IF EXISTS public.inventory CASCADE;
CREATE TABLE public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER VARYING NOT NULL,
    inv_model CHARACTER VARYING NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image CHARACTER VARYING NOT NULL,
    inv_thumbnail CHARACTER VARYING NOT NULL,
    inv_price NUMERIC(10, 2) NOT NULL,
    inv_year INT NOT NULL,
    inv_miles INT,
    inv_color CHARACTER VARYING NOT NULL,
    classification_id INT NOT NULL,
    CONSTRAINT inventory_pk PRIMARY KEY (inv_id),
    CONSTRAINT inventory_fk FOREIGN KEY (classification_id)
        REFERENCES public.classification (classification_id)
);

-- 3. Drop and Create 'account' Table
DROP TABLE IF EXISTS public.account CASCADE;
CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING UNIQUE NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
    account_type public.account_type DEFAULT 'Client',
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);

-- 4. Insert classification data
INSERT INTO public.classification (classification_name) VALUES
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');

-- 5. Insert vehicle inventory records (paths already include /vehicles/)
INSERT INTO public.inventory (
    inv_make, inv_model, inv_description, inv_image, inv_thumbnail,
    inv_price, inv_year, inv_miles, inv_color, classification_id
) VALUES
    ('Lamborghini', 'Adventador', 'A sleek and powerful sports car.', '/images/vehicles/adventador.jpg', '/images/vehicles/adventador-tn.jpg', 450000, 2023, 5000, 'Yellow', 1),
    ('Custom', 'Aerocar', 'A unique flying car from the 1950s.', '/images/vehicles/aerocar.jpg', '/images/vehicles/aerocar-tn.jpg', 200000, 1955, 20000, 'Silver', 1),
    ('Custom', 'Batmobile', 'The iconic vehicle of the Dark Knight.', '/images/vehicles/batmobile.jpg', '/images/vehicles/batmobile-tn.jpg', 1000000, 2023, 1000, 'Black', 1),
    ('Chevrolet', 'Camaro', 'A classic American muscle car.', '/images/vehicles/camaro.jpg', '/images/vehicles/camaro-tn.jpg', 45000, 2022, 15000, 'Blue', 1),
    ('Ford', 'Crown Victoria', 'A reliable former police cruiser.', '/images/vehicles/crwn-vic.jpg', '/images/vehicles/crwn-vic-tn.jpg', 15000, 2011, 80000, 'White', 4),
    ('DMC', 'DeLorean', 'A time-traveling classic with gull-wing doors.', '/images/vehicles/delorean.jpg', '/images/vehicles/delorean-tn.jpg', 75000, 1983, 30000, 'Silver', 1),
    ('Custom', 'Dog Car', 'A quirky car shaped like a dog.', '/images/vehicles/dog-car.jpg', '/images/vehicles/dog-car-tn.jpg', 25000, 2020, 5000, 'Brown', 4),
    ('Cadillac', 'Escalade', 'A luxurious and spacious SUV.', '/images/vehicles/escalade.jpg', '/images/vehicles/escalade-tn.jpg', 85000, 2023, 8000, 'Black', 1),
    ('Custom', 'Fire Truck', 'A vintage fire truck ready for action.', '/images/vehicles/fire-truck.jpg', '/images/vehicles/fire-truck-tn.jpg', 60000, 1970, 40000, 'Red', 3),
    ('GM', 'Hummer', 'A rugged SUV with a huge interior.', '/images/vehicles/hummer.jpg', '/images/vehicles/hummer-tn.jpg', 55000, 2023, 0, 'Black', 2),
    ('Custom', 'Mechanic', 'A car with a mechanic theme.', '/images/vehicles/mechanic.jpg', '/images/vehicles/mechanic-tn.jpg', 30000, 2018, 25000, 'Green', 4),
    ('Ford', 'Model T', 'A historic car that revolutionized the auto industry.', '/images/vehicles/model-t.jpg', '/images/vehicles/model-t-tn.jpg', 35000, 1920, 50000, 'Black', 1),
    ('Custom', 'Monster Truck', 'A massive truck for crushing obstacles.', '/images/vehicles/monster-truck.jpg', '/images/vehicles/monster-truck-tn.jpg', 120000, 2022, 3000, 'Blue', 3),
    ('Custom', 'Mystery Van', 'A van for solving mysteries.', '/images/vehicles/mystery-van.jpg', '/images/vehicles/mystery-van-tn.jpg', 40000, 1969, 60000, 'Green', 4),
    ('Generic', 'No Image', 'A placeholder vehicle with no image.', '/images/vehicles/no-image.png', '/images/vehicles/no-image-tn.png', 10000, 2020, 10000, 'Gray', 4),
    ('Chevrolet', 'Survan', 'A practical suburban van.', '/images/vehicles/survan.jpg', '/images/vehicles/survan-tn.jpg', 35000, 2021, 20000, 'White', 2),
    ('Jeep', 'Wrangler', 'An off-road capable SUV.', '/images/vehicles/wrangler.jpg', '/images/vehicles/wrangler-tn.jpg', 45000, 2023, 5000, 'Green', 2),
    ('Ford', 'Mustang', 'Sporty and fast car.', '/images/vehicles/mustang.jpg', '/images/vehicles/mustang-tn.jpg', 40000, 2022, 10000, 'Red', 1);

-- 6. Insert Tony Stark account
INSERT INTO account (
  account_firstname, 
  account_lastname, 
  account_email, 
  account_password
) VALUES (
  'Tony', 
  'Stark', 
  'tony@starkent.com', 
  'Iam1ronM@n'
);

-- 7. Update Tony Stark to Admin
UPDATE account
SET account_type = 'Admin'
WHERE account_email = 'tony@starkent.com';

-- 8. Delete Tony Stark
DELETE FROM account
WHERE account_email = 'tony@starkent.com';

-- 9. Extra queries for update and join
-- Update GM Hummer description using REPLACE
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Add "/vehicles" to image and thumbnail paths (if not already set)
UPDATE inventory
SET 
  inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
  inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

-- 10. INNER JOIN to get make/model of all "Sport" vehicles
SELECT 
  i.inv_make, 
  i.inv_model, 
  c.classification_name
FROM inventory i
INNER JOIN classification c ON i.classification_id = c.classification_id
WHERE c.classification_name = 'Sport';
